import { ExerciseType } from '../types/workout';

export const DEFAULT_EXERCISES: ExerciseType[] = [
  // === CHEST ===
  {
    id: 'barbell-bench-press',
    name: 'Barbell Bench Press',
    description: 'Lie on a flat bench and press a barbell upward from chest level until arms are extended.',
    primaryMuscleGroups: ['chest'],
    secondaryMuscleGroups: ['triceps', 'shoulders'],
    category: 'strength',
    equipment: ['barbell', 'bench'],
    isCustom: false,
  },
  {
    id: 'incline-dumbbell-press',
    name: 'Incline Dumbbell Press',
    description: 'Press dumbbells upward from an incline bench position to target the upper chest.',
    primaryMuscleGroups: ['chest'],
    secondaryMuscleGroups: ['triceps', 'shoulders'],
    category: 'strength',
    equipment: ['dumbbell', 'bench'],
    isCustom: false,
  },
  {
    id: 'dumbbell-flyes',
    name: 'Dumbbell Flyes',
    description: 'Lie on a flat bench and bring dumbbells together in a wide arc to isolate the chest.',
    primaryMuscleGroups: ['chest'],
    secondaryMuscleGroups: ['shoulders'],
    category: 'strength',
    equipment: ['dumbbell', 'bench'],
    isCustom: false,
  },
  {
    id: 'cable-crossover',
    name: 'Cable Crossover',
    description: 'Pull cable handles together in front of your body from a high pulley position.',
    primaryMuscleGroups: ['chest'],
    secondaryMuscleGroups: ['shoulders'],
    category: 'strength',
    equipment: ['cable'],
    isCustom: false,
  },
  {
    id: 'push-up',
    name: 'Push-Up',
    description: 'Lower and raise your body using your arms while maintaining a straight body position.',
    primaryMuscleGroups: ['chest'],
    secondaryMuscleGroups: ['triceps', 'shoulders', 'abs'],
    category: 'strength',
    equipment: ['bodyweight'],
    isCustom: false,
  },
  {
    id: 'decline-bench-press',
    name: 'Decline Bench Press',
    description: 'Press a barbell from a declined bench position to target the lower chest.',
    primaryMuscleGroups: ['chest'],
    secondaryMuscleGroups: ['triceps', 'shoulders'],
    category: 'strength',
    equipment: ['barbell', 'bench'],
    isCustom: false,
  },

  // === BACK ===
  {
    id: 'barbell-row',
    name: 'Barbell Row',
    description: 'Bend over and pull a barbell toward your lower chest while keeping your back straight.',
    primaryMuscleGroups: ['back', 'lats'],
    secondaryMuscleGroups: ['biceps', 'forearms'],
    category: 'strength',
    equipment: ['barbell'],
    isCustom: false,
  },
  {
    id: 'pull-up',
    name: 'Pull-Up',
    description: 'Hang from a bar and pull your body up until your chin clears the bar.',
    primaryMuscleGroups: ['lats', 'back'],
    secondaryMuscleGroups: ['biceps', 'forearms'],
    category: 'strength',
    equipment: ['pull-up bar'],
    isCustom: false,
  },
  {
    id: 'lat-pulldown',
    name: 'Lat Pulldown',
    description: 'Pull a wide bar down to your upper chest from a seated position.',
    primaryMuscleGroups: ['lats'],
    secondaryMuscleGroups: ['biceps', 'back'],
    category: 'strength',
    equipment: ['cable'],
    isCustom: false,
  },
  {
    id: 'seated-cable-row',
    name: 'Seated Cable Row',
    description: 'Pull a cable handle toward your torso while seated with feet braced.',
    primaryMuscleGroups: ['back'],
    secondaryMuscleGroups: ['biceps', 'lats'],
    category: 'strength',
    equipment: ['cable'],
    isCustom: false,
  },
  {
    id: 'dumbbell-row',
    name: 'Dumbbell Row',
    description: 'Pull a dumbbell toward your hip while supporting yourself with the other hand on a bench.',
    primaryMuscleGroups: ['back', 'lats'],
    secondaryMuscleGroups: ['biceps', 'forearms'],
    category: 'strength',
    equipment: ['dumbbell', 'bench'],
    isCustom: false,
  },
  {
    id: 't-bar-row',
    name: 'T-Bar Row',
    description: 'Straddle a barbell anchored at one end and row the weight toward your chest.',
    primaryMuscleGroups: ['back'],
    secondaryMuscleGroups: ['biceps', 'lats', 'traps'],
    category: 'strength',
    equipment: ['barbell'],
    isCustom: false,
  },

  // === SHOULDERS ===
  {
    id: 'overhead-press',
    name: 'Overhead Press',
    description: 'Press a barbell overhead from shoulder height until arms are fully extended.',
    primaryMuscleGroups: ['shoulders'],
    secondaryMuscleGroups: ['triceps', 'traps'],
    category: 'strength',
    equipment: ['barbell'],
    isCustom: false,
  },
  {
    id: 'lateral-raise',
    name: 'Lateral Raise',
    description: 'Raise dumbbells out to the sides until arms are parallel to the floor.',
    primaryMuscleGroups: ['shoulders'],
    secondaryMuscleGroups: ['traps'],
    category: 'strength',
    equipment: ['dumbbell'],
    isCustom: false,
  },
  {
    id: 'front-raise',
    name: 'Front Raise',
    description: 'Raise dumbbells in front of your body to shoulder height.',
    primaryMuscleGroups: ['shoulders'],
    secondaryMuscleGroups: [],
    category: 'strength',
    equipment: ['dumbbell'],
    isCustom: false,
  },
  {
    id: 'face-pull',
    name: 'Face Pull',
    description: 'Pull a rope attachment toward your face from a high cable position.',
    primaryMuscleGroups: ['shoulders'],
    secondaryMuscleGroups: ['traps', 'back'],
    category: 'strength',
    equipment: ['cable'],
    isCustom: false,
  },
  {
    id: 'arnold-press',
    name: 'Arnold Press',
    description: 'Press dumbbells overhead with a rotation from palms facing you to palms facing forward.',
    primaryMuscleGroups: ['shoulders'],
    secondaryMuscleGroups: ['triceps'],
    category: 'strength',
    equipment: ['dumbbell'],
    isCustom: false,
  },

  // === BICEPS ===
  {
    id: 'barbell-curl',
    name: 'Barbell Curl',
    description: 'Curl a barbell from hip level to shoulder height while keeping elbows stationary.',
    primaryMuscleGroups: ['biceps'],
    secondaryMuscleGroups: ['forearms'],
    category: 'strength',
    equipment: ['barbell'],
    isCustom: false,
  },
  {
    id: 'dumbbell-curl',
    name: 'Dumbbell Curl',
    description: 'Curl dumbbells upward alternately or simultaneously while keeping elbows at your sides.',
    primaryMuscleGroups: ['biceps'],
    secondaryMuscleGroups: ['forearms'],
    category: 'strength',
    equipment: ['dumbbell'],
    isCustom: false,
  },
  {
    id: 'hammer-curl',
    name: 'Hammer Curl',
    description: 'Curl dumbbells with a neutral grip (palms facing each other) to target the brachialis.',
    primaryMuscleGroups: ['biceps'],
    secondaryMuscleGroups: ['forearms'],
    category: 'strength',
    equipment: ['dumbbell'],
    isCustom: false,
  },
  {
    id: 'preacher-curl',
    name: 'Preacher Curl',
    description: 'Curl a barbell or dumbbell while resting your arms on a preacher bench pad.',
    primaryMuscleGroups: ['biceps'],
    secondaryMuscleGroups: [],
    category: 'strength',
    equipment: ['barbell', 'bench'],
    isCustom: false,
  },

  // === TRICEPS ===
  {
    id: 'tricep-pushdown',
    name: 'Tricep Pushdown',
    description: 'Push a cable bar or rope downward from chest height until arms are fully extended.',
    primaryMuscleGroups: ['triceps'],
    secondaryMuscleGroups: [],
    category: 'strength',
    equipment: ['cable'],
    isCustom: false,
  },
  {
    id: 'skull-crusher',
    name: 'Skull Crusher',
    description: 'Lower a barbell or dumbbells toward your forehead from an extended arm position on a bench.',
    primaryMuscleGroups: ['triceps'],
    secondaryMuscleGroups: [],
    category: 'strength',
    equipment: ['barbell', 'bench'],
    isCustom: false,
  },
  {
    id: 'overhead-tricep-extension',
    name: 'Overhead Tricep Extension',
    description: 'Extend a dumbbell or cable overhead from behind your head.',
    primaryMuscleGroups: ['triceps'],
    secondaryMuscleGroups: [],
    category: 'strength',
    equipment: ['dumbbell'],
    isCustom: false,
  },
  {
    id: 'dips',
    name: 'Dips',
    description: 'Lower and raise your body on parallel bars by bending and extending your arms.',
    primaryMuscleGroups: ['triceps'],
    secondaryMuscleGroups: ['chest', 'shoulders'],
    category: 'strength',
    equipment: ['dip bars'],
    isCustom: false,
  },

  // === QUADRICEPS ===
  {
    id: 'barbell-squat',
    name: 'Barbell Squat',
    description: 'Place a barbell on your upper back and squat down until thighs are parallel to the floor.',
    primaryMuscleGroups: ['quadriceps'],
    secondaryMuscleGroups: ['glutes', 'hamstrings', 'abs'],
    category: 'strength',
    equipment: ['barbell', 'squat rack'],
    isCustom: false,
  },
  {
    id: 'leg-press',
    name: 'Leg Press',
    description: 'Push a weighted platform away from your body using your legs from a seated position.',
    primaryMuscleGroups: ['quadriceps'],
    secondaryMuscleGroups: ['glutes', 'hamstrings'],
    category: 'strength',
    equipment: ['machine'],
    isCustom: false,
  },
  {
    id: 'lunges',
    name: 'Lunges',
    description: 'Step forward and lower your body until both knees are bent at 90 degrees.',
    primaryMuscleGroups: ['quadriceps'],
    secondaryMuscleGroups: ['glutes', 'hamstrings'],
    category: 'strength',
    equipment: ['bodyweight', 'dumbbell'],
    isCustom: false,
  },
  {
    id: 'leg-extension',
    name: 'Leg Extension',
    description: 'Extend your legs against resistance from a seated position on a machine.',
    primaryMuscleGroups: ['quadriceps'],
    secondaryMuscleGroups: [],
    category: 'strength',
    equipment: ['machine'],
    isCustom: false,
  },
  {
    id: 'bulgarian-split-squat',
    name: 'Bulgarian Split Squat',
    description: 'Perform a single-leg squat with your rear foot elevated on a bench.',
    primaryMuscleGroups: ['quadriceps'],
    secondaryMuscleGroups: ['glutes', 'hamstrings'],
    category: 'strength',
    equipment: ['dumbbell', 'bench'],
    isCustom: false,
  },

  // === HAMSTRINGS ===
  {
    id: 'romanian-deadlift',
    name: 'Romanian Deadlift',
    description: 'Hinge at the hips to lower a barbell along your legs while keeping them nearly straight.',
    primaryMuscleGroups: ['hamstrings'],
    secondaryMuscleGroups: ['glutes', 'back'],
    category: 'strength',
    equipment: ['barbell'],
    isCustom: false,
  },
  {
    id: 'leg-curl',
    name: 'Leg Curl',
    description: 'Curl your legs against resistance from a prone or seated position on a machine.',
    primaryMuscleGroups: ['hamstrings'],
    secondaryMuscleGroups: ['calves'],
    category: 'strength',
    equipment: ['machine'],
    isCustom: false,
  },
  {
    id: 'good-morning',
    name: 'Good Morning',
    description: 'With a barbell on your back, hinge forward at the hips then return to standing.',
    primaryMuscleGroups: ['hamstrings'],
    secondaryMuscleGroups: ['glutes', 'back'],
    category: 'strength',
    equipment: ['barbell'],
    isCustom: false,
  },

  // === GLUTES ===
  {
    id: 'hip-thrust',
    name: 'Hip Thrust',
    description: 'Drive your hips upward against a barbell while your upper back rests on a bench.',
    primaryMuscleGroups: ['glutes'],
    secondaryMuscleGroups: ['hamstrings'],
    category: 'strength',
    equipment: ['barbell', 'bench'],
    isCustom: false,
  },
  {
    id: 'glute-bridge',
    name: 'Glute Bridge',
    description: 'Lie on your back and raise your hips by squeezing your glutes.',
    primaryMuscleGroups: ['glutes'],
    secondaryMuscleGroups: ['hamstrings'],
    category: 'strength',
    equipment: ['bodyweight'],
    isCustom: false,
  },

  // === CALVES ===
  {
    id: 'standing-calf-raise',
    name: 'Standing Calf Raise',
    description: 'Rise up on your toes from a standing position against resistance.',
    primaryMuscleGroups: ['calves'],
    secondaryMuscleGroups: [],
    category: 'strength',
    equipment: ['machine'],
    isCustom: false,
  },
  {
    id: 'seated-calf-raise',
    name: 'Seated Calf Raise',
    description: 'Rise up on your toes from a seated position with weight on your knees.',
    primaryMuscleGroups: ['calves'],
    secondaryMuscleGroups: [],
    category: 'strength',
    equipment: ['machine'],
    isCustom: false,
  },

  // === ABS ===
  {
    id: 'plank',
    name: 'Plank',
    description: 'Hold a rigid body position supported on your forearms and toes.',
    primaryMuscleGroups: ['abs'],
    secondaryMuscleGroups: ['shoulders'],
    category: 'strength',
    equipment: ['bodyweight'],
    isCustom: false,
  },
  {
    id: 'hanging-leg-raise',
    name: 'Hanging Leg Raise',
    description: 'Hang from a bar and raise your legs until they are parallel to the floor.',
    primaryMuscleGroups: ['abs'],
    secondaryMuscleGroups: ['forearms'],
    category: 'strength',
    equipment: ['pull-up bar'],
    isCustom: false,
  },
  {
    id: 'cable-crunch',
    name: 'Cable Crunch',
    description: 'Kneel in front of a cable machine and crunch downward against resistance.',
    primaryMuscleGroups: ['abs'],
    secondaryMuscleGroups: [],
    category: 'strength',
    equipment: ['cable'],
    isCustom: false,
  },

  // === COMPOUND / FULL BODY ===
  {
    id: 'deadlift',
    name: 'Deadlift',
    description: 'Lift a barbell from the floor to hip height by extending your hips and knees.',
    primaryMuscleGroups: ['back', 'hamstrings', 'glutes'],
    secondaryMuscleGroups: ['quadriceps', 'forearms', 'traps'],
    category: 'strength',
    equipment: ['barbell'],
    isCustom: false,
  },
  {
    id: 'clean-and-press',
    name: 'Clean and Press',
    description: 'Lift a barbell from the floor to your shoulders, then press it overhead.',
    primaryMuscleGroups: ['shoulders', 'back', 'quadriceps'],
    secondaryMuscleGroups: ['triceps', 'glutes', 'traps'],
    category: 'strength',
    equipment: ['barbell'],
    isCustom: false,
  },
  {
    id: 'farmers-walk',
    name: "Farmer's Walk",
    description: 'Carry heavy weights in each hand while walking for distance or time.',
    primaryMuscleGroups: ['forearms', 'traps'],
    secondaryMuscleGroups: ['shoulders', 'abs', 'glutes'],
    category: 'strength',
    equipment: ['dumbbell'],
    isCustom: false,
  },
  {
    id: 'kettlebell-swing',
    name: 'Kettlebell Swing',
    description: 'Swing a kettlebell between your legs and up to chest height using hip drive.',
    primaryMuscleGroups: ['glutes', 'hamstrings'],
    secondaryMuscleGroups: ['back', 'shoulders', 'abs'],
    category: 'strength',
    equipment: ['kettlebell'],
    isCustom: false,
  },

  // === CARDIO ===
  {
    id: 'running',
    name: 'Running',
    description: 'Run at a steady pace or intervals for cardiovascular fitness.',
    primaryMuscleGroups: ['cardio'],
    secondaryMuscleGroups: ['quadriceps', 'hamstrings', 'calves'],
    category: 'cardio',
    equipment: [],
    isCustom: false,
  },
  {
    id: 'cycling',
    name: 'Cycling',
    description: 'Ride a stationary or outdoor bike for cardiovascular fitness.',
    primaryMuscleGroups: ['cardio'],
    secondaryMuscleGroups: ['quadriceps', 'hamstrings'],
    category: 'cardio',
    equipment: ['bike'],
    isCustom: false,
  },
  {
    id: 'rowing-machine',
    name: 'Rowing Machine',
    description: 'Use a rowing machine with full-body pulling and pushing movements.',
    primaryMuscleGroups: ['cardio'],
    secondaryMuscleGroups: ['back', 'biceps', 'quadriceps'],
    category: 'cardio',
    equipment: ['machine'],
    isCustom: false,
  },
  {
    id: 'jump-rope',
    name: 'Jump Rope',
    description: 'Skip rope continuously for cardiovascular conditioning and coordination.',
    primaryMuscleGroups: ['cardio'],
    secondaryMuscleGroups: ['calves', 'shoulders'],
    category: 'cardio',
    equipment: ['jump rope'],
    isCustom: false,
  },
];
